### ISSUE TITLE
AWS: Use `source_ami_filter` instead of `source_ami` for RHEL 7

### ISSUE THREAD

**Issue by przmv** [tidalmigrations/Infrastructure-templates#13]
https://www.packer.io/docs/builders/amazon/ebs#source_ami_filter

**Comment by pranavmalaviya** [comment]
Thanks for flagging this @przmv. We used `source_ami_filter` for [Ubuntu](https://github.com/tidalmigrations/Infrastructure-templates/blob/main/aws/ubuntu/ubuntu-18-04/ubuntu-bionic.pkr.hcl#L39) packer templates. The same need to be done on the RHEL side too. I'll keep this in the front of my mind and address it before releasing the [pipeline trigger](https://github.com/tidalmigrations/machine_stats/pull/134) on machine_stats.
